---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: tgs-sudoku-dev
spec:
  releaseName: sudoku-redis-dev
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: 10.8.1
  values:
    password: testpassword