---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sudoku-dev
  namespace: tgs-sudoku-dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: sudoku-dev
  chart:
    git: git@github.com:urbanmedia/sudoku
    path: kubernetes
    ref: master
  values:
    env: dev

    imagePullSecrets:
      name: dockerhub-deployment
      registry: https://index.docker.io/v1/
      username: tsddevelopers
      password: 'adb9803c-c776-4eda-a69d-f196f99f98ec'

    sudoku:
      repository: tagesspiegel/sudoku
      tag: develop
      replicaCount: 1
      pullPolicy: Always
      redis:
        host: redis-master
        port: 6379
      database:
        host: mysql
        port: 3306
        user: root
        name: sudoku
        proxySql:
          enable: false

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host:  sudoku.localhost
          paths:
            - /

      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local

    resources:
      nginx: {}
      php: {}
    nodeSelector: {}

    tolerations: []

    affinity: {}
  valuesFrom:
    - secretKeyRef:
        name: sudoku-secret
